Pollster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from .views import index, detail, results

app_name = 'polls'

urlpatterns = [
    path('', index, name='index'),
    path('<int:question_id>/detail', detail, name="detail"),
    path('<int:question_id>/results', results, name="results"),
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

polls/views.py
from django.shortcuts import render, get_object_or_404, Http404, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse

# Create your views here.

def index(requests):

    question_list = Question.objects.order_by('-pub_date')
    context = {'question_list': question_list}

    return render(requests, 'polls/index.html', context)


def detail(requests, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Questions does not exist")
    return render(requests, 'polls/detail.html', {'question':question})

def results(requests, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(requests, "polls/results.html", {"question": question})

def vote(requests, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <title>Pollster</title>
  </head>

  <body>
    
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'polls:index' %}">Pollster</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'polls:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin</a>
              </li>
              
          </div>
      </nav>
    </div>
    
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}
          
          {% endblock content %}
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </body>

</html>

templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'polls:vote' %}" class="btn btn-secondary btn-sm mb-3">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
    <p class="alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {csrf_token}
    {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input 
            type="radio" 
            value="{{choice.id}}" 
            id="choice{{forloop.counter}}" 
            name="choice" 
            class="form-check-input" >
            <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
        </div>
    {% endfor %}

    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">

</form>

{% endblock content %}

templates/polls/index.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center mb-3">Poll Questions</h1>
    {% if question_list %}
        {% for question in question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead">{{ question.question_text }}</p>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">View Result</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No questions yet</p>
    {% endif %}

{% endblock content %}

templates/polls/results.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="mb-5 text-center">{{ question.question_text }}</h1>

    <ul class="list-group mb-5">
        {% for choice in question.choice_set.all %}
        <li class="list-group-item">
            {{ choice.choice_text }}
            <span class="badge badge-success float-right">
                {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </span>
        </li>
        {% endfor %}
    </ul>

<a href="{ url 'polls:index'}" class="btn btn-secondary">Back To Polls</a>
<a href="{ url 'polls:detail' question.id }" class="btn btn-dark">Vote again?</a>


{% endblock content %}